In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import joblib
import json

In [2]:
df=pd.read_csv("Telecom_Tower_Failure_Dataset_10000-1.csv")
df.head()

,Tower_ID,Temperature_C,Battery_Voltage,Power_Consumption_W,Signal_Strength_Percent,Fan_Speed_RPM,Humidity_Percent,Traffic_Load,Tower_Age_Years,Failure_Within_48Hrs
0,1,35.6,50.91,2962,56,2838,52,2612,4,0
1,2,43.9,53.33,736,69,3139,36,3427,6,0
2,3,29.0,51.01,2335,50,3117,81,4254,11,1
3,4,39.0,45.62,2808,88,3367,92,1575,7,0
4,5,56.8,51.29,2590,100,1040,25,1336,4,1

In [3]:
X=df[['Tower_ID','Temperature_C','Battery_Voltage','Power_Consumption_W','Signal_Strength_Percent','Fan_Speed_RPM','Humidity_Percent','Traffic_Load','Tower_Age_Years']]
y=df['Failure_Within_48Hrs']

In [4]:
X

,Tower_ID,Temperature_C,Battery_Voltage,Power_Consumption_W,Signal_Strength_Percent,Fan_Speed_RPM,Humidity_Percent,Traffic_Load,Tower_Age_Years
0,1,35.6,50.91,2962,56,2838,52,2612,4
1,2,43.9,53.33,736,69,3139,36,3427,6
2,3,29.0,51.01,2335,50,3117,81,4254,11
3,4,39.0,45.62,2808,88,3367,92,1575,7
4,5,56.8,51.29,2590,100,1040,25,1336,4
...,...,...,...,...,...,...,...,...,...
9995,9996,59.9,45.79,1847,47,3200,24,2206,12
9996,9997,69.8,53.99,2322,74,3175,74,2022,9
9997,9998,51.7,47.93,2289,81,3380,36,4467,9
9998,9999,69.3,46.58,1747,57,2689,30,4561,15
9999,10000,46.3,45.93,972,45,3012,22,4738,7

In [5]:
y

0       0
1       0
2       1
3       0
4       1
       ..
9995    1
9996    1
9997    0
9998    1
9999    1
Name: Failure_Within_48Hrs, Length: 10000, dtype: int64

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [7]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [8]:
model.fit(X_train,y_train)
accuracy=model.score(X_test,y_test)
print("Accuracy of random forest",accuracy)

Accuracy of random forest 1.0

In [9]:
joblib.dump(model,"telecom_tower_model.pkl")

['telecom_tower_model.pkl']

In [11]:
metrics={"accuracy":accuracy}
with open("metrics.json","w") as f:
    json.dump(metrics,f,indent=4)
print("Training Completed Successfully")

Training Completed Successfully